## Numpy Tutorial

In [4]:
import numpy as np

In [8]:
##Creating Arrays from Python Lists
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

B: Numpy will only accept arrays with the same data types, otherwise it will upcast

In [9]:
## Explicitly set the data type of the resulting array

np.array([2,4,6,8], dtype='float32')

array([2., 4., 6., 8.], dtype=float32)

In [11]:
#Creating Arrays from scracth
# Create a length-15 interger array filled with zeros

np.zeros(15, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Create a length-10 interger array filled with ones
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 30, stepping by 2

np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [17]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
#Create 5 random intergers between 0 and 15

In [20]:
np.random.randint(0,15, 5)

array([ 7,  8,  2, 11,  9])

### NumPy Array Attributes


In [22]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [25]:
print(x1)

[5 0 3 3 7 9]


In [26]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [28]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


#### ndim, shape and size attributes

In [29]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


#### dtype attribute

In [31]:
print("dtype:", x3.dtype)

dtype: int32


#### itemsize attribute 

Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array:



In [32]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


### Array Indexing: Accessing Single Elements


In [33]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
##Access the first index
x1[0]

5

In [35]:
#Access the last index 
x1[-1]

9

In [36]:
#Access the second last index 
x1[-2]

7

### Array Slicing: Accessing Subarrays

The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x[:5] #access the first 5 elements

array([0, 1, 2, 3, 4])

In [39]:
x[5:]  # elements after index 5


array([5, 6, 7, 8, 9])

In [40]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [41]:
x[::2]  # every other element, with 2 steps

array([0, 2, 4, 6, 8])

In [42]:
x[1::2]  # every other element, starting at index 1


array([1, 3, 5, 7, 9])

In [43]:
x[::-1]  # all elements, reversed


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

When a negative step is used, the default order of start and stop are reversed accordingly/swapped

### Accessing array rows and columns

In [44]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [47]:
print(x2[0, :])  # first row of x2

[3 5 2 4]


In [48]:
print(x2[0])  # equivalent to x2[0, :]

[3 5 2 4]


### Concatenation of arrays


In [49]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

### Splitting of arrays


The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:



In [50]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]
